// Code generated by projectspec-gen; DO NOT EDIT.

package config

import fwconfig "github.com/he11ah0und/config"

// Accessor is a typed, live facade over a *fwconfig.Sheet: every
// field is a cell handle, so reads and writes through the accessor go
// straight to the sheet and stay in sync with the rest of the app.
type Accessor struct {
	Core    *CoreAccessor
	Configs *ConfigsAccessor
	Log     *LogAccessor
	UI      *UIAccessor
	Updates *UpdatesAccessor
	Plugins *PluginsAccessor
	Service *ServiceAccessor
	Remote  *RemoteAccessor
}

type CoreAccessor struct {
	AutoRestart          *fwconfig.Cell
	TrafficGraphHistory  *fwconfig.Cell
	ConnectionsRetention *fwconfig.Cell
	URLTestURL           *fwconfig.Cell
	StartOnLaunch        *fwconfig.Cell
	Log                  *CoreLogAccessor
	Proxy                *CoreProxyAccessor
}

type CoreLogAccessor struct {
	Level *fwconfig.Cell
}

type CoreProxyAccessor struct {
	Enabled *fwconfig.Cell
}

type ConfigsAccessor struct {
	DeleteCacheOnRemove *fwconfig.Cell
}

type LogAccessor struct {
	Level *fwconfig.Cell
	Limit *fwconfig.Cell
}

type UIAccessor struct {
	ShowLogs             *fwconfig.Cell
	Language             *fwconfig.Cell
	ConnectionsSort      *fwconfig.Cell
	DesktopNotifications *fwconfig.Cell
	Theme                *fwconfig.Cell
	ThemeMode            *fwconfig.Cell
}

type UpdatesAccessor struct {
	AutoCheckSelf                      *fwconfig.Cell
	AutoCheckCore                      *fwconfig.Cell
	AutoUpdateConfigs                  *fwconfig.Cell
	AutoUpdateConfigsIntervalHours     *fwconfig.Cell
	AutoUpdateOnHashMismatch           *fwconfig.Cell
	AutoRestartOnConfigUpdate          *fwconfig.Cell
	BackgroundUpdateCheckIntervalHours *fwconfig.Cell
	DefaultIntervalHours               *fwconfig.Cell
}

type PluginsAccessor struct {
	Enabled   *fwconfig.Cell
	Developer *fwconfig.Cell
}

type ServiceAccessor struct {
	Backend          *fwconfig.Cell
	StartOnAppLaunch *fwconfig.Cell
	StopOnAppExit    *fwconfig.Cell
}

type RemoteAccessor struct {
	DefaultTransport       *fwconfig.Cell
	LastTcpAddress         *fwconfig.Cell
	LastConnectionMode     *fwconfig.Cell
	RememberConnectionMode *fwconfig.Cell
	LastPassphrase         *fwconfig.Cell
}

// NewAccessor binds the accessor tree to sheet.
func NewAccessor(sheet *fwconfig.Sheet) *Accessor {
	return &Accessor{
		Core: &CoreAccessor{
			AutoRestart:          sheet.MustGet("core", "auto_restart"),
			TrafficGraphHistory:  sheet.MustGet("core", "traffic_graph_history"),
			ConnectionsRetention: sheet.MustGet("core", "connections_retention"),
			URLTestURL:           sheet.MustGet("core", "url_test_url"),
			StartOnLaunch:        sheet.MustGet("core", "start_on_launch"),
			Log: &CoreLogAccessor{
				Level: sheet.MustGet("core", "log", "level"),
			},
			Proxy: &CoreProxyAccessor{
				Enabled: sheet.MustGet("core", "proxy", "enabled"),
			},
		},
		Configs: &ConfigsAccessor{
			DeleteCacheOnRemove: sheet.MustGet("configs", "delete_cache_on_remove"),
		},
		Log: &LogAccessor{
			Level: sheet.MustGet("log", "level"),
			Limit: sheet.MustGet("log", "limit"),
		},
		UI: &UIAccessor{
			ShowLogs:             sheet.MustGet("ui", "show_logs"),
			Language:             sheet.MustGet("ui", "language"),
			ConnectionsSort:      sheet.MustGet("ui", "connections_sort"),
			DesktopNotifications: sheet.MustGet("ui", "desktop_notifications"),
			Theme:                sheet.MustGet("ui", "theme"),
			ThemeMode:            sheet.MustGet("ui", "theme_mode"),
		},
		Updates: &UpdatesAccessor{
			AutoCheckSelf:                      sheet.MustGet("updates", "auto_check_self"),
			AutoCheckCore:                      sheet.MustGet("updates", "auto_check_core"),
			AutoUpdateConfigs:                  sheet.MustGet("updates", "auto_update_configs"),
			AutoUpdateConfigsIntervalHours:     sheet.MustGet("updates", "auto_update_configs_interval_hours"),
			AutoUpdateOnHashMismatch:           sheet.MustGet("updates", "auto_update_on_hash_mismatch"),
			AutoRestartOnConfigUpdate:          sheet.MustGet("updates", "auto_restart_on_config_update"),
			BackgroundUpdateCheckIntervalHours: sheet.MustGet("updates", "background_update_check_interval_hours"),
			DefaultIntervalHours:               sheet.MustGet("updates", "default_interval_hours"),
		},
		Plugins: &PluginsAccessor{
			Enabled:   sheet.MustGet("plugins", "enabled"),
			Developer: sheet.MustGet("plugins", "developer"),
		},
		Service: &ServiceAccessor{
			Backend:          sheet.MustGet("service", "backend"),
			StartOnAppLaunch: sheet.MustGet("service", "start_on_app_launch"),
			StopOnAppExit:    sheet.MustGet("service", "stop_on_app_exit"),
		},
		Remote: &RemoteAccessor{
			DefaultTransport:       sheet.MustGet("remote", "default_transport"),
			LastTcpAddress:         sheet.MustGet("remote", "last_tcp_address"),
			LastConnectionMode:     sheet.MustGet("remote", "last_connection_mode"),
			RememberConnectionMode: sheet.MustGet("remote", "remember_connection_mode"),
			LastPassphrase:         sheet.MustGet("remote", "last_passphrase"),
		},
	}
}
